debug: False


ctrl:
  MODE: 'video'  # 'camera'
  DETECT: True
  RECORDING: True
  GUI: True
  ANCHOR: True

  SENDING: True
  RECEIVING: False

  MAP: False
  CALIB: False
  SAVE_CSV: False
  SAVE_IMG: False

  CHESSBOARD: False

video:
  bin_video_root: './video'
  bin_video_left: './video/left.mp4'
  bin_video_right: './video/right.mp4'

weights:
  yolov8: './weights/yolov8/0801_sumup_80.pt'

ui:
  image_w: 1280
  image_h: 640

portx: 'COM7'